### ISSUE TITLE
Doesn't update unless turning the plugin off and back on

### ISSUE THREAD

**Issue by SimplyFrankie** [BobTabrizi/market-watcher#1]
Would be nice to have a button to refresh the prices or have it auto refresh at a user set interval.

**Comment by BobTabrizi** [comment]
Prices get updated after either enabling the plugin _**or**_ relaunching RL. I generally never have RL open long enough to have noticed this so thanks for bringing this to my attention. I'll be adding a setting option with the next version to define auto refresh intervals with a base interval of 12h.

**Comment by BobTabrizi** [comment]
Prices get updated after either enabling the plugin or relaunching RL. I generally never have RL open long enough to have noticed this, so thanks for bringing this to my attention. I'll be adding a setting option with the next version to define auto refresh intervals with a default interval of 12h.

**Comment by BobTabrizi** [comment]
This feature has been added in V1.1.0, which is now merged.

**Comment by SimplyFrankie** [comment]
Is there any way to be able to set shorter intervals than 6 hours?

**Comment by BobTabrizi** [comment]
There is. I just don't know why that would be necessary if the lowest time period you can track items for is 24h. Can you give me a use case for an interval less than 6h?
