### ISSUE TITLE
Don't block the client thread

### ISSUE THREAD

**Issue by YvesW** [BobTabrizi/market-watcher#2]
FYI your code blocks the client thread, then takes a lock on the client thread, and then performs 3 synchronous http requests. You probably want to fix that so we don't get #support traffic complaining about clients freezing.

**Comment by BobTabrizi** [comment]
That's a good point. Overlooked this when introducing the fetches after client initialization... I'll look into resolving this. Thanks!

**Comment by BobTabrizi** [comment]
Resolved in e8d258d8bcee6b9227d2e4f863e1a3e37c450a80
