### ISSUE TITLE
Add button that allows you to manually refresh the prices

### ISSUE THREAD

**Issue by SimplyFrankie** [BobTabrizi/market-watcher#3]
Would be nice to have a button to press to refresh the prices if we can't set the refresh interval to 60s like the real-time wiki prices page.

**Comment by BobTabrizi** [comment]
I'd really prefer to not have a refresh button... I am open to lowering the refresh interval to 60s instead if you can give me a use case. Since you already asked for this in the original issue I'll be closing this one and await your response on #1 .
